name: PHP Documentor
on:
  push:
    branches:
      main
jobs:
      despliegue:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: phpdoc-box-action
            uses: phpDocumentor/phar-ga@1.0.0
          - name: Inicializa phpDoc
            run:
              php phpDocumentor.phar run -d ./ -t docs
