name: PHP Documentor
on:
  push:
    branches:
      main
jobs:
      despliegue:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: descarga phpDoc
            run: wget https://phpdoc.org/phpDocumentor.phar
          - name: Inicializa phpDoc
            run:
              chmod +x phpDocumentor.phar
              mv phpDocumentor.phar /usr/local/bin/phpDocumentor
